### ISSUE TITLE
Upgrade Support for Ecto 3.0

### ISSUE THREAD

**Issue by BenGiese22** [annkissam/rummage_ecto#85]
Hey there! Trying to use your Pagination Library for my project. 

Would be cool if you could update and support Ecto 3.0.0+?

```
Failed to use "ecto" (version 3.0.6) because
  ecto_sql (version 3.0.4) requires ~> 3.0.6
  phoenix_ecto (version 4.0.0) requires ~> 3.0
  rummage_ecto (version 2.0.0-rc.0) requires ~> 2.2
  mix.lock specifies 3.0.6
```

**Comment by aditya7iyengar** [comment]
Hi @BenGiese22 we're currently working on v2.0 release, which has ecto 3.0 compatibility. Sorry it's taking so long, but things keep changing and we're trying to reach a stable place with both ecto and phoenix.

**Comment by BenGiese22** [comment]
Sounds great! Looking forward to your release.
